---
title: "git learn"
author: "PED/QA/Mech"
date: "28/08/2022"
output: pdf_document
---

```{r setup, include=FALSE}
#knitr::opts_chunkset(echo = TRUE)
```

xaringan::infinite_moon_reader()

git config --list    # list everythnng !!# Show repository configuration:
          
git config  --list  --local  #    --global ,  --system  
git config --global user.name "[firstname lastname]"
git config --global user.email "[valid-email]"
git config --global color.ui auto # Set automatic command line coloring 
git config --global core.editor vi

#Configuration Files
/etc/gitconfig      ## - System-wide config file [--system]:
   ~/.gitconfig        ## - User-specific config file [--global]:
<repo>/.git/config  ## - Repository specific config file [--local]:


git init 
git init <directory>
git clone ssh://user@domain.com/repo.git
git clone http://domain.com/user/repo.git


git status
git diff  Changes to tracked files:
git diff <file>  # See changes/difference of a specific file:

# A text search on all files in the directory:
git grep "Hello"
# In any version of a text search:    
git grep "Hello" v2.5


git add .
git add -p <file>  # Add some changes in <file> to the next commit:
git add <filename1> <filename2> # Add only the mentioned files to the next commit:

# Commit all local changes in tracked files:   
git commit -a
git commit -m 'message here'  # Commit with message: 
git commit -am 'message here' # Commit skipping the staging area and adding message:
git commit --date="`date --date='n day ago'`" -am "<Commit Message>" # Commit to previous dates
git commit -a --amend  # Change last commit: 

#  Rename files
git mv Index.txt Index.html

# Search  git grep "Hello"
git grep "Hello" v2.5 # In any version of a text search:

# Commit History  
git log
git log --oneline
git log --author="username"
git log -p <file>           # Show changes over time for a specific file:
git log --oneline <origin/master>..<remote/master> --left-right # Display commits present only in remote/branch in right side

git log -S 'keyword'                 # Show commits that introduced a specific keyword
git log -S 'keyword' --pickaxe-regex # usig regexp

git blame <file>  #  Who changed, what and when in <file>:
git reflog show   #  Show Reference log: 
git reflog delete #  Delete Reference log:


## Create a new branch based on your current HEAD:
git branch <new-branch>  
# Branches 
git branch     # List all local branches:
git branch -a  # List local/remote branches
git branch -r  # List all remote branches:

## Switch HEAD branch:
git checkout     <branch>
git checkout -b  <branch>  ## Create and switch new branch:
git checkout <branch> -- <filename> ## Checkout single file from different branch
git checkout -           ## Switch to previous:
git checkout -b <new_branch> <existing_branch> ## Created from exiting branch and switch

## Created from exiting branch and switch
git checkout <commit-hash> -b <new_branch_name>

## Create a new tracking branch based on a remote branch:
git branch --track <new-branch> <remote-branch>


## Rename current branch to new branch name
git branch -m <new_branch_name>

## Delete a local branch:
git branch -d <branch>
git branch -D <branch>   ## Force delete local branch: lose unmerged changes!



# Move uncommitted changes from current branch to some other branch:
git stash
git checkout branch2
git stash pop
git stash apply   # Restore stashed changes back to current branch:

# Restore particular stash back to current branch:
  
git stash list # to get {stash_number}
git stash apply stash@{stash_number}
git stash drop  #  Remove the last set of stashed changes:



## Mark HEAD with a tag:
git tag <tag-name>
## Mark HEAD with a tag and open the editor to include a message:
git tag -a <tag-name>
## Mark HEAD with a tag that includes a message:
git tag <tag-name> -am 'message here'

## List all tags:
git tag
git tag -n ## List all tags with messages or commit message if no tag message

# Update & Publish

## List all current configured remotes:
git remote -v
git remote show   <remote>        ## Show information about a remote:
git remote add    <remote> <url>  ## Add new remote repository, named <remote>:
git remote rename <remote> <new_remote> ## Rename a remote repository
git remote rm     <remote>        ## simply removes remote and its references from local repo.

## Download all changes from <remote>, but don't integrate into HEAD:
git fetch       <remote>
## Download changes and directly merge/integrate into HEAD:
git remote pull <remote> <url>
## Get all changes from HEAD to local repository:
git pull origin master
## Get all changes from HEAD to local repository without a merge:
git pull --rebase <remote> <branch>

## Publish local changes on a remote:
git push <remote> <branch>
## Delete a branch on the remote:
git push <remote> :<branch> (since Git v1.5.0)
## OR
git push <remote> --delete <branch> (since Git v1.7.0)

## Publish your tags:
git push --tags

## Configure the merge tool globally to meld (editor)
git config --global merge.tool meld
## Use your configured merge tool to solve conflicts:
git mergetool

# Merge & Rebase
## Merge branch into your current HEAD:
git merge <branch>
## List merged branches
git branch --merged

## Rebase your current HEAD onto <branch>:
### Don't rebase published commit!
git rebase <branch>
git rebase --abort  ## Abort a rebase:
git rebase --continue  ## Continue a rebase after resolving conflicts:
## Use your editor to manually solve conflicts and (after resolving) mark file as resolved:
git add <resolved-file>
git rm <resolved-file>

Squashing commits:
git rebase -i <commit-just-before-first>
Now replace this,
pick <commit_id>
pick <commit_id2>
pick <commit_id3>
  to this,
  
pick <commit_id>
  squash <commit_id2>
  squash <commit_id3>
  Undo


# Descard
## Discard all local changes in your working directory:
git reset --hard HEAD
## Remove all the files out of the staging area(i.e. undo the last git add):
git reset HEAD
## Discard local changes in a specific file:
git checkout HEAD <file>
## Revert a commit (ie new commit with contrary changes):
git revert <commit>

## Reset your HEAD pointer to a previous commit and discard all changes since then:
git reset --hard <commit>

## Reset your HEAD pointer to a remote branch current state.
git reset --hard <remote/branch>   e.g., upstream/master, origin/my-feature

## Reset your HEAD pointer to a previous commit and preserve all changes as unstaged changes:
git reset <commit>

## Reset your HEAD pointer to a previous commit and preserve uncommitted local changes:
git reset --keep <commit>

## Remove files that were accidentally committed before they were added to .gitignore
git rm -r --cached .
git add .
git commit -m "remove xyz file"




