---
title: "The Diesel Loco Performance"
author: "Gopal Kumar$^1$"
date: "`r Sys.Date()`"
output:
  beamer_presentation: 
    incremental: yes
    highlight: tango
  revealjs::revealjs_presentation:  #separate pkg
    toc: true
  word_document:
    toc: yes
  ioslides_presentation:
    incremental: yes
    highlight: tango
  slidy_presentation:
    incremental: yes
    highlight: tango
  pdf_document:
    toc: yes
  html_document: default
  '': default
institute: $^1$CMPE(Diesel)
header-includes:
- \usepackage{xcolor}
- \usepackage{framed}
---
<!--
(naming one of the output formats from your YAML), or
bookdown::render_book("index.Rmd", 
                      output_format = bookdown::pdf_document2(latex_engine = "xelatex"))

--->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
#<!---
You can change colors also within a frame.
\setbeamercolor{block title}{use=structure,fg=white,bg=purple!75!black}
\setbeamercolor{block body}{use=structure,fg=black,bg=white!20!white}
#--->

<!---
\setbeamercolor{block title}{use=structure,fg=black,bg=purple!55!black}
\setbeamercolor{block body}{use=structure,fg=white,bg=blue!20!white}
--->

# The meeting agenda

- Discussion on Compliance of last meeting Minutes

## contd 
- Preparedness of winter Drive.
- Innovation & good work done in sheds during last Six months. 
- Implementation of Action plan targets for 2017-18 including plan issued by Railway Board


# Performance Statistics 

\colorlet{shadecolor}{red!30} 
\begin{shaded}
Black text with a red background.
\end{shaded}

\colorlet{shadecolor}{red!60} 

## Direct PL /100ML/Month    Apr-Sept

  : Direct PL /100ML/Month    Apr-Sept.

| Shed | 2016 | 2017 | % improvement|
|------|------:|------:|------:|
| TKD  |12.6 | 7.2 | 42.9 |
| LDH | 8.0 | 5.5 | 31.8 |
| LKO | 17.9 | 12.3 | 31.3|
| NR | 12.2 | 8.0 | 34.4 |
| IR | 9.2 | 7.7 | 16.7|

  


\colorlet{shadecolor}{red!90} 

\begin{shaded}

Black text with a darker red background.

\end{shaded}



QO-D-8.1-11 Vendor - Changes in approved status


4.1.1 Prerequisites

 a) The vendor has applied in writing to RDSO for upgradation from "List of RDSO Vendors for developmental order" posted on RDSO website to "List of Approved Vendors". 

b) The Vendor should meet either criteria i) or criteria ii) below: 

Criteria i) The vendor should have supplied minimum specified quantity (N) of material as specified by the concerned Design/QA directorate as a ”List of RDSO Vendors for developmental order" posted on RDSO website vendor 
To be in service for a minimum period of one year. or 15 months from the date of issue of last inspection certificate. 

12/15 months from time  N Qty completed while him being dev vendor


Criteria ii) “Equipment Months" on basis of in service period can also be considered as qualifying criteria for upgradation. 

If “N" is the minimum specified quantity then minimum Equipment Months for upgradation from date of in service = 12 N or Minimum Equipment Months for up-gradation from date of issue of inspection certificate = 15 N
However, for up-gradation under ii) on basis of „Equipment Months" shall not be given before 15 months from date of issue of inspection certificate for N/2th item.

Criteria whichever is earlier complied with from i) or ii) above can be considered for up-gradation.


Note: Where minimum specified in service period specified is more than mentioned in para (b) (i) above, the equipment months criteria shall be change accordingly e.g. if for an item minimum specified period is 18 months then equipment month will change by factor of 18/12 = 1.5 i.e. 12 N becomes 12X 1.5 = 18N and 15N becomes 15 X 1.2 = 22.5N.


N and T specified by directorate





c) Each Directorate must specify minimum quantity for each item in their directorate procedures for upgradation 

For certain critical & safety items where it is not possible to evaluate the performance, unless it is monitored upto next overhaul/sufficient period, the directorate head shall prepare the exception list specifying the period for such items and include it in the directorate procedures. If, at any stage directorate need to change the minimum quantity for upgradation, then proposal for same with justification shall be send to Spl. DG/VD for approval. 

d) mandatory requirement :Vendor should possess valid ISO 9001 certificate for manufacture of same/similar item at his works address. 

e) The name of the firm should appear in “List of Vendors for Development Orders". 




f) Service Performance - 
The performance of the firm should be satisfactory. 
The performance criteria for each item shall be decided by the Directorate head taking into account the criteria laid down by the concerned design directorate, like limiting FRPCPY as per the formula for calculating the FRPCPY of the item (where ever applicable) as under: 

FRPCPY = {(No. Of failures * 100*12) /(Population*Period in months)} 

The performance reports received through web portal of RDSO/through official email (no manual feedback should be asked for) up to the date of eligibility of the firm shall be taken as performance criteria for considering up gradation.  
Directorate Head shall take up the issue with concerned PHODs of zonal Railways on regular basis. 
(Reference: - DG/RDSO"s DO No. 13/vig/Policy dated 13/11/2014 & CVO/RDSO"s Note No. Comp/8.02.10 dated 31/03/2016)

g) In exceptional circumstances where waiver of laid down conditions for upgradation of firm is required, the same will require prior approval of Spl. DG/VD/RDSO.


Note: 
Many equipment/items which have RDSO specifications but vendor approval is not done by RDSO are procured by railways on their own. Inclusion of such items as identified by Railway Board in RDSO approved list shall be done by inviting EOI for vendor registration in which existing firms can also participate. 

However, after approval of existing firms in “List of RDSO Vendors for developmental order" posted on RDSO website, the mandatory period of one year for upgradation of firm to “List of Approved Vendors" can be dispensed with in case firm has already supplied minimum quantity for upgradation from “List of RDSO Vendors for developmental order" posted on RDSO website to “List of Approved Vendors" and performance of product supplied earlier was satisfactory


4.1.2 Time period for applying for upgradation 
The firms classified as „List of RDSO Vendors for developmental order" posted on RDSO website on the vendor list can apply maximum six months in advance of the date due for upgradation. The applications which are received between three to six months in advance of the due date for upgradation shall be processed. However status shall be upgraded on the due date subject to the condition that all laid down criteria has been complied with. If any sample is under testing at RDSO, the result of the test shall be considered. 

Applications received less than three months in advance of the due date of upgradation, shall be processed. However, delay if any in upgradation with respect to due date, shall be attributable to the late receipt of application.



4.1.3 Suo moto upgradation of the developmental vendors: 
“On receipt of information at RDSO by the concerned directorate that a Developmental Vendor has fulfilled the upgradation criteria as stipulated at para 4.1.1 above, after completion of 5 years period from the date of entering into vendor directory as Developmental vendor (without any quantity restriction ), the Directorate will initiate, Suo moto the process of upgradation of the developmental vendor as Approved Vendor and informed the vendor to be in readiness for Bidding/Supplying larger quantities as expected from an Approved Vendor for that item. 

Letter conveying enlistment as developmental vendor to every new firm henceforth will bear a validity of 05 years period. 
After lapse of 4 year period from the registration , firm has to provide details to RDSO about efforts/ orders executed during the last 4 year period and based on the merit of the case, concerned Directorate may extend validity of the firm"s status as Developmental source for further 02 years / may consider for upgrading as approved source.


4.1.4: After seven-year period as Developmental Vendor status (without any quantity restriction), if the firm fails to comply with the stipulated upgradation requirements, the firm will be delisted from the list of developmental vendors. 

A one time relaxation period of 03 years will be given to all vendors whose registration status is being affected or expected to be affected in next 03 years from the date of issue of this amendment.



