---
title: "Testing inclusion of child doc"
subtitle: "yes for testing"
date: "25 feb 2020"
output:
  pdf_document: default
  html_document: default
---
# Pattern matching

Now pattern matching

> gregexpr(pattern, text, ignore.case = FALSE, perl = FALSE,          fixed = FALSE, useBytes = FALSE)
> gsub("(\\w)(\\w*)", "\\U\\1\\L\\2", txt, perl=TRUE)



> strings <- c(  "apple",   "219 733 8965",   "329-293-8753",  "Work: 579-499-7527; Home: 543.355.3679" )

> phone <- "([2-9][0-9]{2})[- .]([0-9]{3})[- .]([0-9]{4})"

> str_detect(strings, phone) : Logical :  [1] FALSE  TRUE  TRUE  TRUE : str_count() 
> str_subset(strings, phone) : string:  [1] "219 733 8965" [2] "329-293-8753"  [3] "Work: 579-499-7527; Home: 543.355.3679"

> str_locate_all(strings, phone)  ;location of match position
> str_extract(strings, phone)  [1] NA  "219 733 8965" "329-293-8753" "579-499-7527"
> str_extract_all(strings, phone)
# What are the phone numbers?
str_extract(strings, phone)
#> [1] NA             "219 733 8965" "329-293-8753" "579-499-7527"

> str_extract_all(strings, phone, simplify = TRUE) : better  simple list


> str_match_all() extracts capture groups from all matches and returns a list of character matrices like regmatches().

> str_replace() replaces the first matched pattern and returns a character vector. 
> str_replace_all() replaces all matches with second "string". Similar to sub() , gsub().
> str_replace(strings, phone, "XXX-XXX-XXXX")  : "Work: XXX-XXX-XXXX; Home: 543.355.3679"
> str_replace_all(strings, phone, "XXX-XXX-XXXX")

> str_split("a-b-c", "-") : "a" "b" "c"
> str_split_fixed("a-b-c", "-", n = 2) : fixed 2 only as : "a"  "b-c"
